#*******************************************************************
# $Id: Makefile,v 1.1 2001/07/09 13:05:48 johblo Exp $
#*******************************************************************

# Requires UCS version 0.2 or later. 
SOWAPSTACK_RELEASE_VERSION = 0.9

MAKE_ENVIRON = \
	'SOWAPSTACK_RELEASE_VERSION=$(SOWAPSTACK_RELEASE_VERSION)'

all:
	cd src; make all $(MAKE_ENVIRON)

clean:
	cd src; make clean

